// Teaches the generated Android project how to sign a release build with a real
// upload key.
//
// WHY THIS FILE EXISTS
// -------------------
// `android/` is not committed — it is regenerated by `expo prebuild` on every build
// (Continuous Native Generation), so any edit made directly inside it is discarded.
// Expo's template hardcodes:
//
//     release {
//         signingConfig signingConfigs.debug     // <- debug key, not distributable
//     }
//
// and, unlike the bare React Native template, it provides no property-driven release
// signingConfig to hook into. So the only durable place to make this change is a config
// plugin, which runs *during* prebuild and therefore survives regeneration.
//
// HOW THE KEYSTORE REACHES GRADLE
// -------------------------------
// Through Gradle properties passed on the command line (`-PST_UPLOAD_STORE_FILE=...`),
// never through a file. Nothing secret is written to disk in the repo, and
// `gradle.properties` — which prebuild regenerates anyway — stays untouched.
//
// If those properties are absent the build falls back to the debug key, so the existing
// local `./gradlew assembleRelease` convenience still works. That fallback is a real
// footgun (a debug-signed APK installs fine and cannot be distributed), so it warns
// loudly at configuration time, and CI additionally verifies the finished APK's signer
// certificate fingerprint — see the "Verify signer" step in
// `.github/workflows/android-build.yml`. Belt and braces on purpose: this exact mistake
// is already recorded in the project's own README as a known trap.

// Required lazily, inside the plugin function, so that the pure transform below can be
// exercised by scripts/check-release-signing-plugin.js without node_modules present.
// Presence of this marker makes the transform idempotent — prebuild can run repeatedly
// (and `--clean` or not) without stacking duplicate blocks.
const MARKER = "sarkaritaiyaari:release-signing";

const SIGNING_CONFIGS_ANCHOR = "signingConfigs {";

// The release buildType's signing line, verbatim from Expo's template. Anchoring on the
// two comment lines above it is what distinguishes it from the *debug* buildType's
// identical `signingConfig signingConfigs.debug`.
const BUILD_TYPE_ANCHOR = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_SIGNING_CONFIG = `
        // ${MARKER} — injected by plugins/withReleaseSigning.js
        // Populated only when CI passes the -P properties; otherwise left empty and the
        // buildType below falls back to the debug key.
        release {
            if (project.hasProperty('ST_UPLOAD_STORE_FILE')) {
                storeFile file(project.property('ST_UPLOAD_STORE_FILE'))
                storePassword project.property('ST_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('ST_UPLOAD_KEY_ALIAS')
                keyPassword project.property('ST_UPLOAD_KEY_PASSWORD')
            }
        }`;

const RELEASE_BUILD_TYPE = `            // ${MARKER} — injected by plugins/withReleaseSigning.js
            if (project.hasProperty('ST_UPLOAD_STORE_FILE')) {
                signingConfig signingConfigs.release
            } else {
                logger.warn("WARNING: signing this release build with the DEBUG key. " +
                    "It will install, but it is NOT distributable and cannot upgrade a " +
                    "properly signed install. Pass -PST_UPLOAD_STORE_FILE to use the " +
                    "real upload key.")
                signingConfig signingConfigs.debug
            }`;

function injectReleaseSigning(contents) {
  if (contents.includes(MARKER)) {
    return contents;
  }

  if (!contents.includes(SIGNING_CONFIGS_ANCHOR)) {
    throw new Error(
      "[withReleaseSigning] Could not find `signingConfigs {` in app/build.gradle. " +
        "Expo's template has probably changed shape — update plugins/withReleaseSigning.js. " +
        "Failing here on purpose: silently skipping would produce a debug-signed APK " +
        "that looks fine and cannot be shipped."
    );
  }

  if (!contents.includes(BUILD_TYPE_ANCHOR)) {
    throw new Error(
      "[withReleaseSigning] Found `signingConfigs {` but not the release buildType's " +
        "signing block. Expo's template has changed — update the BUILD_TYPE_ANCHOR " +
        "constant in plugins/withReleaseSigning.js to match the new text."
    );
  }

  return contents
    .replace(SIGNING_CONFIGS_ANCHOR, SIGNING_CONFIGS_ANCHOR + RELEASE_SIGNING_CONFIG)
    .replace(BUILD_TYPE_ANCHOR, RELEASE_BUILD_TYPE);
}

module.exports = function withReleaseSigning(config) {
  const { withAppBuildGradle } = require("expo/config-plugins");

  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        `[withReleaseSigning] Expected a Groovy build.gradle, got "${cfg.modResults.language}".`
      );
    }
    cfg.modResults.contents = injectReleaseSigning(cfg.modResults.contents);
    return cfg;
  });
};

// Exported for the unit check in scripts/check-release-signing-plugin.js, which runs the
// transform against a fixture so an Expo upgrade breaks a fast test rather than a build.
module.exports.injectReleaseSigning = injectReleaseSigning;
module.exports.MARKER = MARKER;
