export {
  ALGORITHM_VERSION,
  EVIDENCE_WINDOW_DAYS,
  RECENT_WINDOW_DAYS,
  MIN_WINDOW_ATTEMPTS,
  HALF_LIFE_DAYS,
  RECENCY_FLOOR,
  MIN_PYQ_ATTEMPTS,
  IMPROVING_DELTA,
  DECLINE_DELTA,
  buildDifficultyScale,
  scoreTopicHealth,
  resolveState,
  evidenceLevelFor,
  renormalise,
  recencyWeight,
  consistencyOf,
} from "./topicHealth";
export type {
  TopicHealthState,
  EvidenceLevel,
  PerformanceTrend,
  EvidenceEvent,
  TopicHealthResult,
  DifficultyScale,
} from "./topicHealth";
export type {
  TopicHealthStateName,
  RadarOverviewStatus,
  RadarOverview,
  ActionStep,
  RecommendedActionName,
  RadarReasonCode,
  PrerequisiteRef,
  RadarTopic,
  WeaknessRadar,
  RadarSource,
  RadarResult,
} from "./types";
